---
# tasks file for ssh_hardening
- name: Backup existing sshd config
  ansible.builtin.copy:
    src: /etc/ssh/sshd_config.d/10-hardening.conf
    dest: /etc/ssh/sshd_config.d/10-hardening.conf.bak
    remote_src: true
    owner: root
    group: root
    mode: '0600'
  ignore_errors: true

- name: Add authorized keys
  when: ssh_hardening_authorized_keys | length > 0
  ansible.builtin.include_tasks:
    file: add_keys.yml
  loop: "{{ ssh_hardening_authorized_keys_users }}"

- name: Configure sshd
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: /etc/ssh/sshd_config.d/10-hardening.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload ssh service

- name: Force all notified handlers
  ansible.builtin.meta: flush_handlers

- name: Get sshd -T output
  ansible.builtin.command: sshd -T
  register: sshd_output
  changed_when: false
  check_mode: false

- name: Render sshd config template to a variable
  ansible.builtin.set_fact:
    rendered_template: "{{ lookup('template', 'sshd.conf.j2') }}"
  delegate_to: localhost
  changed_when: false
  check_mode: false

- name: Verify each line is in the sshd -T output
  ansible.builtin.assert:
    that: "item|lower in sshd_output.stdout"
    fail_msg: "FAIL: The line '{{ item }}' was not found in the 'sshd -T' output."
    success_msg: "PASS: The line '{{ item }}' was found in the 'sshd -T' output."
  loop: "{{ rendered_template.splitlines() }}"
  when: item | trim != '' and not item.startswith('#')
  ignore_errors: true

- name: Ensure fail2ban is installed
  when: ssh_hardening_enable_fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Configure fail2ban for sshd
  when: ssh_hardening_enable_fail2ban
  ansible.builtin.template:
    src: fail2ban-sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart fail2ban

- name: Install dependencies
  when: ssh_hardening_enable_tg_notifications
  ansible.builtin.package:
    name:
      - curl
      - tzdata
      - jq
    state: present

- name: Upload notifications on login script
  when: ssh_hardening_enable_tg_notifications
  ansible.builtin.template:
    src: pam-notify.sh.j2
    dest: /usr/local/bin/pam-notify.sh
    owner: root
    group: root
    mode: '0755'

- name: Configure PAM for notifications
  when: ssh_hardening_enable_tg_notifications
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    line: "session optional pam_exec.so /usr/local/bin/pam-notify.sh"
