---
# handlers file for ssh_hardening
- name: Restart ssh service
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: restarted
